### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by talantbekov123** [DmitryForsilov/DmitryForsilov.github.io#1]
Хорошая работа, нужно сделать не большие исправления, что бы была корректная валидация примеров ниже.

**Отлично**
- эфективное регулярное выражение
- работа на github pages, все поля работают
- нет лишних файлов в репозитории
- требования к веткам соблюдены

**Надо исправить**
- Должно быть 3 ветки проекта. Добавить ветки: gh-pages, develop
- `review.test@yandex.ru` - В почте может присутствовать точка
- `http://google.ru///1///2///3` - количество слешей в пути должно быть ограничено одним экземпляром для каждой части пути
- `http://ya.ru:00000` - Проверку проходит следующий некорректный адре сайта. (в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными). Подробнее про порты можно почитать [тут](https://buy.fineproxy.org/articles/chto-takoe-port-servera.html)

**Comment by DmitryForsilov** [comment]
- Добавил две ветки в репозиторий. До этого они у меня были в проекте. То есть, я все мерджил в редакторе и пушил с мастер-ветки.

- Добавил фикс для валидации имени. Теперь точка может присутствовать в имени почты до "@".

- Добавил фикс для валидации url. 
  1) В одной секции пути может быть только один слеш.
  2) Изменил сегмент регулярного выражения для корректной проверки введеного порта.

**Comment by talantbekov123** [comment]
Хорошая работа, все комментарии исправленны! Похвально! Принимаю.
